Wip:Schedule pages
spbgti/schedule-frontend pull request #7
Opened 2019-10-19 13:28 UTC by aleasper

Add routing for scheudle table and change table from vue-tables to vuetify-interators

2019-10-19 14:00 UTC, b0g3r requested changes

2019-10-19 14:00 UTC, b0g3r commented on src/components/Schedule.vue
> +          <tr
Утеряны отступы у td и пропсов.

Было:
```
          <tr
          @click="selectGroup(props.item.group_id, props.item.number, props)"
          :style="[selectedNumber === props.item.group_id ? {'background': 'rgba(68, 219, 252, 0.2)'} : {'background': '#FFF'}]"
          >
          <td>{{ props.item.number }}</td>
          <td>{{ props.item.group_id }}</td>
          </tr>
```

Должно быть:
```
          <tr
            @click="selectGroup(props.item.group_id, props.item.number, props)"
            :style="[selectedNumber === props.item.group_id ? {'background': 'rgba(68, 219, 252, 0.2)'} : {'background': '#FFF'}]"
          >
            <td>{{ props.item.number }}</td>
            <td>{{ props.item.group_id }}</td>
          </tr>
```

2019-10-19 14:00 UTC, b0g3r commented on src/components/Schedule.vue
> +  components: {
Лишнее

2019-10-19 14:00 UTC, b0g3r commented on src/components/ScheduleDay.vue
> +  timeOfPairs = [['9:30', '11:10'],
утеряны отступы:
```
  timeOfPairs = [
    ['9:30', '11:10'],
    ['11:30', '13:10'],
    ['14:00', '15:40'],
    ['16:00', '17:40'],
    ['18:00', '19:40'],
    ['time1', 'time2'],
  ];
```

2019-10-19 14:00 UTC, b0g3r commented on src/components/SchedulePair.vue
> +      >{{ name }}, {{ type }}</v-card>
Тут во всём темплейте поехали отступы:
```
      <v-card
        class="font-weight-black"
        :elevation="0"
        v-if="type != ''"
      >
        {{ name }}, {{ type }}
      </v-card>
```
Общее правило:
```
<tag
  :props=props
>
  content
</tag>
```

2019-10-19 14:00 UTC, b0g3r commented on src/components/SchedulePair.vue
> +        v-if="type != ''"
v-if лучше ставить на первое место среди пропсов

2019-10-19 14:00 UTC, b0g3r commented on src/components/ScheduleWeek.vue
> +  evenDaysSchedule: Array<Array<IExercise>> = [[],[],[],[],[]]; // chetn
На подумать: возможно структура в виде словаря (Map/object) с полями-номерами дней была бы лучше

2019-10-19 14:00 UTC, b0g3r commented on src/components/ScheduleWeek.vue
> +  parity: string = "";
Лучше назвать по смыслу, excludedParity или переписать функцию сортировки, вынеся логику туда

2019-10-19 14:08 UTC, aleasper commented on src/components/SchedulePair.vue
> +        v-if="type != ''"
> v-if лучше ставить на первое место среди пропсов

Это соглашение о стиле или помогает избегать излишней нагрузки из-за последовательного выполнения сверху-вниз?

2019-10-19 23:10 UTC, reflash commented on src/components/ScheduleWeek.vue
> +    switch (parity) {
Можно таким образом попробовать :-)
```suggestion
    let daysSchedule;
switch (parity){
	case "!2":
    	daysSchedule = this.evenDaysSchedule;
    case "!1":
    	daysSchedule = this.oddDaysSchedule;
}
let dayIdx = parseInt(exercise.day) - 1;
if (daysSchedule && dayIdx >=0 && dayIdx < 5)
  daysSchedule.push(exercise)
```

2019-10-21 09:02 UTC, aleasper commented on src/components/ScheduleWeek.vue
> +    switch (parity) {
Немного не понял как это должно работать: подразумевается, что в конце функции мы по условию присвоим либо `this.evenDaysSchedule`, либо `this.oddDaysSchedule` значение `daysSchedule`?

2019-10-21 09:10 UTC, reflash commented on src/components/ScheduleWeek.vue
> +    switch (parity) {
Именно, референс сохранится в `daysSchedule`.

2019-10-21 11:08 UTC, aleasper commented on src/components/ScheduleWeek.vue
> +    switch (parity) {
Это точно будет выгоднее?
```
    let daysShedule;
    switch(parity){
      case "!2":
        daysShedule = this.evenDaysSchedule;
        break;
      case "!1":
        daysShedule = this.oddDaysSchedule;
        break;
    }
    let dayIdx = parseInt(exercise.day) - 1;
    if (daysShedule && dayIdx >= 0 && dayIdx <= 5){
      daysShedule[dayIdx].push(exercise)
    }
    switch(parity){
      case "!2":
        this.evenDaysSchedule.push(daysShedule[0]);
        break;
```
Сначала мы объявляем двумерный массив, а потом используем единственный его элемент для присвоения. Ф-я, в которой вызывается этот код, используется для каждого эл-а расписания 
```
let orderedExercises = this.orderedItems(this.exercises)
for (let i = 0; i != orderedExercises.length; ++i){
   this.setDaysSchedule(orderedExercises[i], "!2");
}
```

2019-10-21 12:21 UTC, reflash commented on src/components/ScheduleWeek.vue
> +    switch (parity) {
Я думаю, что если и есть разница в перформансе - она пренебрежимо мала, особенно учитывая размер `orderedExercises.length`, взамен этого код получается короче.

2019-10-22 18:25 UTC, reflash commented on src/components/ScheduleWeek.vue
> +    switch(parity){
Я думаю я не точно описал, что я имел в виду :-) 131 - 138 строки не нужны, все что было нужно уже делается в предыдущих

2019-10-23 08:29 UTC, aleasper commented on src/components/ScheduleWeek.vue
> +    switch(parity){
Как в evenDaysSchedule и oddDaysSchedule идёт присвоение? Плохо понял этот момент

2019-10-23 08:51 UTC, reflash commented on src/components/ScheduleWeek.vue
> +    switch(parity){
daysShedule сохраняет в себе ссылку на evenDaysSchedule или oddDaysSchedule и `daysShedule[dayIdx].push(exercise)` пушит значение в соответствующий Array

2019-10-23 08:55 UTC, aleasper commented on src/components/ScheduleWeek.vue
> +    switch(parity){
Спасибо, почитаю подробнее про ссылки в js\ts: до этого о них не знал

2019-10-23 08:59 UTC, merged